### ISSUE TITLE
Feature Request:  Compatibility with Rocketry Expanded

### ISSUE THREAD

**Issue by LawOfSynergy** [modo-lv/oni-mod-demolish-neutronium#2]
[Rocketry Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2837919908) introduces Neutronium Dust which is acquired by cleaning off artifacts and is used to create neutronium alloy.

It would be awesome if mining neutronium either dropped Neutronium Dust directly (when the mod is detected), or a config option is provided to allow neutronium to be dropped and a recipe can be added to the crusher to crush neutronium into neutronium dust (this recipe could be provided by RE).

**Comment by modo-lv** [comment]
I have taken a bit of hiatus from ONI since one of their updates broke like half the mods I was playing with sometime last year, and have no *immediate* plans to get back into it. But I plan to go back eventually, and I see no reason not add an option for enabling neutronium dust to the mod when I do.

**Comment by LawOfSynergy** [comment]
Sure!

In the base mod, you get 10kg of neutronium dust for every artifact that gets cleaned up in the artifact analyzer.
10kg of neutronium dust is combined with 90kg of steel to get 100kg of neutronium alloy, which can be used as a refined metal for anything that requires refined metal.

**Comment by modo-lv** [comment]
All resources are ultimately infinite if provided by care packages, and at the end of the day anyone who really wants to cheat can just add some infinity resource mod to have whatever they want. I was thinking about the "normal" progression/difficulty curve of RE, which I would like my mod to enrich without breaking.

For example, if Rocketry Expanded is built with a kind of balance in mind where you gain Neutronium slowly over time, bit by bit, artifact by artifact (so that special rocket modules or total insulation a limited resource you have to use sparingly), suddenly acquiring tons of it by just cleaning up the side of the map seems like an overkill.

Unfortunately I haven't played Rocketry Expanded before and have just started a completely new colony, so it will be a while before I reach any kind of space travel. I have no idea what the actual game progression with RE is supposed to be (in terms of Neutronium). I should probably find some time to play around with it in Sandbox mode, but I don't know when that'll be.

How much Neutronium Dust do you normally get from cleaning a single artifact?

**Comment by LawOfSynergy** [comment]
You get 10kg of neutronium dust from cleaning a single artifact.

**Comment by modo-lv** [comment]
Implemented in version 1.1.0.

**Comment by LawOfSynergy** [comment]
You are Awesome! Thank you!!
